#include<stdio.h>
int main()
{
    int r,c,i,j,arr[100][100],sum=0,h=0,p=0,sum2=0;
    scanf("%d%d",&r,&c);
    for(i=0;i<r;i++)
    {
        for(j=0;j<c;j++)
        {
            scanf("%d",&arr[i][j]);
        }
    }
    for(i=0;i<r;i++)
    {
        sum=0;
        for(j=0;j<c;j++)
        {
            sum=sum+arr[i][j];
        }
    if(h<sum)
    {
        h=sum;
    }
      }
     for(j=0;j<c;j++)
     {
         sum2=0;
         for(i=0;i<r;i++)
         {
             sum2=sum2+arr[i][j];
         }
         if(p<sum2)
         {
             p=sum2;
         }
     }
     if(h>p)
     {
         printf("%d",h);
     }
     else
     {
         printf("%d",p);
     }
}